In [3]:
# Import dataset

import pandas as pd 

df = pd.read_csv('fraud_risk_dataset.csv')

#view data 
df.head()

,transaction_id,customer_age,account_tenure_months,region,transaction_amount,merchant_category,payment_method,device_type,num_transactions_24h,international,previous_chargebacks,fraud
0,100000,65,68,South,130.13,Travel,Digital Wallet,Tablet,4,0,0,0
1,100001,22,4,South,28.27,Travel,Debit,Tablet,1,0,0,0
2,100002,43,53,South,304.83,Travel,Credit,Tablet,2,0,0,0
3,100003,72,69,West,39.87,Restaurants,Debit,Tablet,1,0,1,1
4,100004,21,8,South,125.73,Gas,Debit,Desktop,3,0,0,0

In [4]:
# In this notebook we will begin look at the why fraud occurs

In [5]:
# Test 1 

df.groupby('international')['fraud'].mean()

international
0    0.051554
1    0.191489
Name: fraud, dtype: float64

In [6]:
# Foreign transactions see an increase in the amount of fraud

In [21]:
# Test 2
df.groupby('num_transactions_24h')['fraud'].mean()

num_transactions_24h
0     0.058915
1     0.075565
2     0.069096
3     0.068182
4     0.076763
5     0.063584
6     0.200000
7     0.291667
8     0.000000
9     0.000000
10    0.000000
Name: fraud, dtype: float64

In [9]:
# There is a increase of recorded fraud on transactions that are gretater than 5

In [10]:
#Test 3

df.groupby('previous_chargebacks')['fraud'].mean()

previous_chargebacks
0    0.068826
1    0.052915
2    0.256579
3    0.416667
4    0.000000
5    0.000000
Name: fraud, dtype: float64

In [12]:
# Repeated offenders of charge backs = reapted fraud

In [13]:
# test 4 
df.groupby('device_type')['fraud'].mean()

device_type
Desktop    0.069378
Mobile     0.076145
Tablet     0.072253
Name: fraud, dtype: float64

In [14]:
# Tablets and mobile phone pose a huge risk for fraud

In [15]:
#Test 5 
df['age_group'] = pd.cut(
    df['customer_age'],
    bins = [18, 25, 35, 45, 55, 65, 100])

df.groupby('age_group')['fraud'].mean()

C:\Users\dmiracju\AppData\Local\Temp\ipykernel_12324\3611114656.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('age_group')['fraud'].mean()

age_group
(18, 25]     0.075472
(25, 35]     0.074944
(35, 45]     0.061998
(45, 55]     0.082424
(55, 65]     0.069351
(65, 100]    0.069320
Name: fraud, dtype: float64

In [17]:
# Age between 18 - 25 pose the highest risk for fraudulent transactions, second would be 25 - 35. 
# Young adults are likely to commit fraudulent transactions

In [18]:
# Test 6 
pd.crosstab(df['payment_method'], df['international'], values = df['fraud'], aggfunc='mean')

international          0         1
payment_method
Credit          0.046076  0.219512
Debit           0.052120  0.169492
Digital Wallet  0.056338  0.185185

In [ ]:
# The highest ammount of fraud on average is being done by foreigners using credit transactions

In [24]:
df['velocity'] = pd.cut(
    df['num_transactions_24h'], bins = [2,5,8,10]
)

df.groupby('velocity')['fraud'].mean()

C:\Users\dmiracju\AppData\Local\Temp\ipykernel_12324\3710466116.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('velocity')['fraud'].mean()

velocity
(2, 5]     0.070358
(5, 8]     0.223529
(8, 10]    0.000000
Name: fraud, dtype: float64

In [ ]:
# Test 7 

df.corr(numeric_only=True)

,transaction_id,customer_age,account_tenure_months,transaction_amount,num_transactions_24h,international,previous_chargebacks,fraud
transaction_id,1.000000,-0.009198,0.019090,0.018491,0.009575,-0.014645,0.010954,-0.019129
customer_age,-0.009198,1.000000,-0.015166,0.004277,0.000972,-0.011690,0.004446,-0.006536
account_tenure_months,0.019090,-0.015166,1.000000,-0.003644,0.002887,0.002499,0.006306,-0.004756
transaction_amount,0.018491,0.004277,-0.003644,1.000000,-0.008851,0.013351,-0.004573,0.121474
num_transactions_24h,0.009575,0.000972,0.002887,-0.008851,1.000000,0.012728,0.012258,0.034891
international,-0.014645,-0.011690,0.002499,0.013351,0.012728,1.000000,-0.016846,0.192778
previous_chargebacks,0.010954,0.004446,0.006306,-0.004573,0.012258,-0.016846,1.000000,0.079443
fraud,-0.019129,-0.006536,-0.004756,0.121474,0.034891,0.192778,0.079443,1.000000

In [ ]:
# Fraud likelihood increases sharply for international transactions and customers with chargeback history.
# Mobile devices show higher fraud rates compared to desktops or tablets.
# Transaction velocity strongly elevates risk up to medium-high levels.
# High-value categories such as luxury show persistent fraud exposure.
# Geography and payment behavior are superior predictors over demographics.